import Head from 'next/head'
import './globals.css'
import { Inter } from 'next/font/google'
import toast, { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        {/* Manifest file */}
        <link rel="manifest" href="/manifest.json" />
        {/* Meta tags */}
        <meta name="theme-color" content="#000000" />
      </Head>
      <body className={inter.className}>
        <div className="bg-gray-900 w-full">
          <Toaster />
          {children}
        </div>
      </body>
    </html>
  )
}
